version: "3"
tasks:
  sample-azure-cosmos-service:
    desc: "Runs the Azure Cosmos Service sample"
    cmds:
      - uv run python -m samples.azure_cosmos_service

  sample-azure-openai-service:
    desc: "Runs the Azure OpenAI Service sample"
    cmds:
      - uv run python -m samples.azure_openai_service

  sample-azure-blob-storage-service:
    desc: "Runs the Azure Blob Storage Service sample"
    cmds:
      - uv run python -m samples.azure_blob_storage_service
  sample-azure-content-safety-service:
    desc: "Runs Azure Content Safety Service sample"
    cmds:
      - uv run python -m samples.azure_content_safety_service

  sample-azure-keyvault-service:
    desc: "Runs the Azure Key Vault Service sample"
    cmds:
      - uv run python -m samples.azure_keyvault_service

  sample-azure-mlflow-service:
    desc: "Runs the Azure MLFlow Service sample"
    cmds:
      - uv run python -m samples.azure_mlflow_service

  sample-azure-foundry-adv-sim:
    desc: "Runs the Azure Foundry Adversarial Simulation sample"
    cmds:
      - uv run python -m samples.azure_foundry_adv_sim

  sample-adversarial-simulation-service:
    desc: "Runs the Adversarial Simulation Service sample"
    cmds:
      - uv run python -m samples.adversarial_simulation_service

  sample-embedding-service:
    desc: "Runs the Embedding Service sample"
    cmds:
      - uv run python -m samples.embedding_service

  sample-azure-managed-redis-service:
    desc: "Runs the Azure Managed Redis Service sample"
    cmds:
      - uv run python -m samples.azure_managed_redis_service

  sample-azure-text-analytics-service:
    desc: "Runs the Azure AI Text Analytics Service sample"
    cmds:
      - uv run python -m samples.azure_text_analytics_service

  sample-azure-defender-service:
    desc: "Runs the Azure Defender Service sample"
    cmds:
      - uv run python -m samples.azure_defender_service

  sample-azure-resources-query-service:
    desc: "Runs the Azure Resources Query sample"
    cmds:
      - uv run python -m samples.azure_resources_query_service

  sample-azure-text2speech-service:
    desc: "Runs the Azure Text to Speech Service sample"
    cmds:
      - uv run python -m samples.azure_text2speech_service

  test-unit:
    desc: "Runs unit tests with pytest"
    cmds:
      - uv run python -m pytest -p no:warnings --cov-report term-missing
        --cov=azure_python tests

  util-format-code:
    desc: "Formats the code using ruff"
    cmds:
      - uv run ruff format .

  util-lint:
    desc: "Runs linting with Ruff"
    cmds:
      - uv run ruff check .
      - uv run pyright .

  util-gen-requirements-txt:
    desc: "Generates requirements.txt from the current environment"
    cmds:
      - uv lock
      - uv export --frozen --no-dev --output-file=requirements.txt
      - uv export --frozen --all-groups --output-file=requirements.dev.txt

  util-pip-audit:
    desc: "Runs pip-audit to check for vulnerabilities"
    cmds:
      - uv run pip-audit -r requirements.txt
      - uv run pip-audit -r requirements.dev.txt
