trigger:
  - main

pool:
  vmImage: "ubuntu-latest"
strategy:
  matrix:
    Python313:
      python.version: "3.13"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
    displayName: "Use Python $(python.version)"
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install -r requirements.dev.txt
    displayName: "Install dependencies"
  # Run linters
  - script: |
      echo "Running ruff..."
      ruff check .
      echo "Running pyright..."
      pyright .
    displayName: "Run linters"
    condition: succeededOrFailed()
  # Run package scanning
  - script: |
      pip-audit -r requirements.txt
    displayName: "Run package scanning"
    condition: succeededOrFailed()
  - script: |
      python -m pytest --doctest-modules --junitxml=junit/test-results.xml --cov=python_guide --cov-report=xml tests
    displayName: "Run tests"
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: "junit/test-*.xml"
      testRunTitle: "Publish test results for Python $(python.version)"
    displayName: "Publish test results"
  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/coverage.xml"
    displayName: "Publish coverage results"


